_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.18
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
alpha:
    value: 0.3
arch:
    value: alexnet
batch_size:
    value: 64
beta:
    value: 0.5
biased:
    value: false
buffer_size:
    value: 1000
classes:
    value: 100
compress:
    value: false
dataset:
    value: cifar100
derpp_flag:
    value: true
deterministic:
    value: true
device:
    value: 0
frac:
    value: 1
increment_th:
    value: 0.001
level:
    value: 32
local_epochs:
    value: 30
lr:
    value: 0.01
method:
    value: svd
momentum:
    value: 0
n_clients:
    value: 1
num_tasks:
    value: 10
port:
    value: "29500"
print_times:
    value: 5
run_no:
    value: 1
save_dir:
    value: save_temp
save_every:
    value: 5
seed:
    value: 1
skew:
    value: 0
wandb:
    value: true
weight_decay:
    value: 0
workers:
    value: 4
